spring.application.name=springboot

spring.datasource.url=jdbc:mysql://localhost:3306/supermercado
spring.datasource.username=root
spring.datasource.password=Lebronjames2210!

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


mercadopago.access.token=TEST-XXXXXXXXXXXXXXX

jwt.secret=VkmsDXySmMP1hkVKFyq0bbAM32N392ruHSDAmJ0KjgM=
jwt.expiration=86400000 
