spring.application.name=springboot

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/supermercado}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

mercadopago.access.token=${MERCADOPAGO_TOKEN:TEST-XXXXXXXXXXXXXXX}

jwt.secret=${JWT_SECRET:VkmsDXySmMP1hkVKFyq0bbAM32N392ruHSDAmJ0KjgM=}
jwt.expiration=${JWT_EXPIRATION:86400000}

spring.kafka.bootstrap-servers=${KAFKA_SERVERS:localhost:9092}

spring.kafka.consumer.group-id=springboot-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer